name: heatingapp

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883 #default mqtt port
    # - 9001:9001 #default mqtt port for websockets
    volumes:
      - ./mqtt/config:/mosquitto/config:rw
      - ./mqtt/data:/mosquitto/data:rw
      - ./mqtt/log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      - heatingapp
  caddy:
    image: caddy:2-alpine
    ports:
      - 3000:3000
      - 80:80
      - 8081:8081
      - 81:81
      - 443:443
      #- 1884:1883
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - heatingapp
  python_gpio:
    user: root
    build:
      context: ./python_gpio
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ./python:/pythondata
    networks:
      - heatingapp
volumes:
  mariadb_data:
  config:
  data:
  log:
  caddy_data:
  caddy_config:

networks:
  heatingapp:
    driver: bridge
