name: heatingapp

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883 #default mqtt port
      - 9001:9001 #default mqtt port for websockets
    volumes:
      - /home/markus/mqtt/config:/mosquitto/config:rw
      - /home/markus/mqtt/data:/mosquitto/data:rw
      - /home/markus/mqtt/log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      - heatingapp
  mariadb:
    image: mariadb:11.4.10
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data:/data/db
    networks:
      - heatingapp
    environment:
      MYSQL_ROOT_PASSWORD: kingroot
      MYSQL_DATABASE: heatingdb
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
        # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
        # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_3680e523ea73ef11acb6db1e313510fd-if00-port0:/dev/ttyUSB0
    networks:
      - heatingapp
  server: 
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: heatingAppServer
    # restart: unless-stopped
    env_file: ./server/.env
    volumes: 
    - ./server:/app
    - /app/node_modules
    ports: 
      - 3000:3000
    networks:
      - heatingapp
    depends_on:
      - mariadb
      - mosquitto
      - zigbee2mqtt
  frontend: 
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: heatingApp
    # restart: unless-stopped
    env_file: ./frontend/.env
    volumes: 
    - ./frontend:/app
    - /app/node_modules
    ports: 
      - 5173:5173
    command: npm run start -- --host
    networks:
      - heatingapp
    depends_on:
      - mariadb
      - server
      - mosquitto
      - zigbee2mqtt
  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - heatingapp
    depends_on:
      - frontend
  
volumes:
  mariadb_data:
  config:
  data:
  log:
  caddy_data:
  caddy_config:

networks:
  heatingapp:
    driver: bridge
      